
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.sql.*;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;




public class menu extends javax.swing.JFrame {

    Conexion conn;
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int id;
    private String nombreUsuario;
    
    
    
    
    public menu() {
        initComponents();
        conn = new Conexion();  // Instanciar la conexión
        conn.conectar();
        verificarStockBajo();
        this.setTitle("MENU");
        
        cargarPanelPorDefecto();
        
    }

    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
        lblUser.setText("Bienvenido, " + nombreUsuario);  // Mostrar el nombre en el JLabel
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUsuarios = new javax.swing.JButton();
        btnCategorias = new javax.swing.JButton();
        btnCaracteristicas = new javax.swing.JButton();
        btnCrearproducto = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnEspecificacion = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        btnAlertas = new javax.swing.JComboBox<>();
        lblUser = new javax.swing.JLabel();
        btnHistorial = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnInformes = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(46, 46, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUsuarios.setBackground(new java.awt.Color(13, 110, 253));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("CREAR USUARIO");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, 40));

        btnCategorias.setBackground(new java.awt.Color(13, 110, 253));
        btnCategorias.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCategorias.setForeground(new java.awt.Color(255, 255, 255));
        btnCategorias.setText("CREAR CATEGORIA");
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });
        jPanel1.add(btnCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 157, 40));

        btnCaracteristicas.setBackground(new java.awt.Color(13, 110, 253));
        btnCaracteristicas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCaracteristicas.setForeground(new java.awt.Color(255, 255, 255));
        btnCaracteristicas.setText("CARACTERISTICAS PRO.");
        btnCaracteristicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaracteristicasActionPerformed(evt);
            }
        });
        jPanel1.add(btnCaracteristicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, 40));

        btnCrearproducto.setBackground(new java.awt.Color(13, 110, 253));
        btnCrearproducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCrearproducto.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearproducto.setText("CREAR PRODUCTO");
        btnCrearproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearproductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 157, 40));

        jButton1.setBackground(new java.awt.Color(13, 110, 253));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INGRESO STOCK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 157, 41));

        btnEspecificacion.setBackground(new java.awt.Color(13, 110, 253));
        btnEspecificacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEspecificacion.setForeground(new java.awt.Color(255, 255, 255));
        btnEspecificacion.setText("ESPECIFICACIONES");
        btnEspecificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspecificacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnEspecificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 157, 40));

        btnVenta.setBackground(new java.awt.Color(13, 110, 253));
        btnVenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnVenta.setText("VENTA PRODUCTOS");
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 157, 40));

        jPanel1.add(btnAlertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 190, 30));

        lblUser.setText("jLabel1");
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));

        btnHistorial.setBackground(new java.awt.Color(13, 110, 253));
        btnHistorial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHistorial.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorial.setText("HISTORIAL PRODUCTO");
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        jPanel1.add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 157, 40));

        btnPedidos.setBackground(new java.awt.Color(13, 110, 253));
        btnPedidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPedidos.setForeground(new java.awt.Color(255, 255, 255));
        btnPedidos.setText("PEDIDOS");
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });
        jPanel1.add(btnPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 157, 40));

        btnInformes.setBackground(new java.awt.Color(13, 110, 253));
        btnInformes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInformes.setForeground(new java.awt.Color(255, 255, 255));
        btnInformes.setText("INFORMES");
        btnInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformesActionPerformed(evt);
            }
        });
        jPanel1.add(btnInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 157, 40));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Método para cargar el panel por defecto
    private void cargarPanelPorDefecto() {
        crearUsuarios p1 = new crearUsuarios();  // Instancia del panel por defecto
        p1.setSize(680, 592);
        p1.setLocation(0, 0);
        
        content.removeAll();  // Limpiar cualquier contenido previo en el panel 'content'
        content.add(p1, BorderLayout.CENTER);  // Añadir el panel por defecto al contenedor
        content.revalidate();  // Volver a validar el contenedor
        content.repaint();     // Volver a repintar el contenedor para reflejar los cambios
    }
    
    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
        crearCategoria p2 = new crearCategoria();
        p2.setSize(680, 592);
        p2.setLocation(0, 0);
        
        content.removeAll();
        content.add(p2, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnCaracteristicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaracteristicasActionPerformed
        crearCaracteristicass p3 = new crearCaracteristicass();
        p3.setSize(680, 592);
        p3.setLocation(0, 0);
        
        content.removeAll();
        content.add(p3, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnCaracteristicasActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        crearUsuarios p1 = new crearUsuarios();
        p1.setSize(680, 592);
        p1.setLocation(0, 0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnEspecificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspecificacionActionPerformed
        crearEspecificaciones p4 = new crearEspecificaciones();
        p4.setSize(680, 592);
        p4.setLocation(0, 0);
        
        content.removeAll();
        content.add(p4, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnEspecificacionActionPerformed

    private void btnCrearproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearproductoActionPerformed
        crearProducto p5 = new crearProducto();
        p5.setSize(680, 592);
        p5.setLocation(0, 0);
        
        content.removeAll();
        content.add(p5, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnCrearproductoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        stock p6 = new stock(nombreUsuario);
        p6.setSize(680, 592);
        p6.setLocation(0, 0);
        
        content.removeAll();
        content.add(p6, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    void verificarStockBajo() {
        try {
            // Limpiar el combobox de alertas previas
            btnAlertas.removeAllItems();

            // Consulta para obtener los productos con stock bajo
            String sql = "SELECT nombreProducto, stock FROM productos WHERE stock <= 5";
            cn = conn.getConnection();
            PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            // Si existen productos con stock bajo, llenar el combobox
            while (rs.next()) {
                String nombreProducto = rs.getString("nombreProducto");
                int stockActual = rs.getInt("stock");

                // Añadir el producto y el stock actual al combobox
                btnAlertas.addItem("Producto: " + nombreProducto + " - Stock: " + stockActual);
            }

            // Si no hay productos con stock bajo, mostrar un mensaje
            if (btnAlertas.getItemCount() == 0) {
                btnAlertas.addItem("No hay productos con stock bajo");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al verificar el stock: " + e.getMessage());
        }
    }
    
    
    
    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        ventas p7 = new ventas(nombreUsuario);
        p7.setSize(680, 592);
        p7.setLocation(0, 0);
        
        content.removeAll();
        content.add(p7, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        historial p8 = new historial();
        p8.setSize(680, 592);
        p8.setLocation(0, 0);
        
        content.removeAll();
        content.add(p8, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        pedidos p9 = new pedidos();
        p9.setSize(680, 592);
        p9.setLocation(0, 0);
        
        content.removeAll();
        content.add(p9, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformesActionPerformed
        informesYgraficas p10 = new informesYgraficas();
        p10.setSize(680, 592);
        p10.setLocation(0, 0);
        
        content.removeAll();
        content.add(p10, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnInformesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                // Mostrar un mensaje cuando la interfaz gráfica esté visible
            System.out.println("Interfaz gráfica inicializada.");
                new menu().setVisible(true);  
                
                System.out.println("Programa iniciado.");

        Timer timer = new Timer(2000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("El Timer está funcionando cada 2 segundos...");
            }
        });

        System.out.println("Iniciando el Timer...");
        timer.start();

        // Hacemos que el programa corra indefinidamente para que el Timer siga activo
        while (true) {
            // No hacemos nada, solo dejamos que el Timer siga funcionando
        }
            }
        });
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> btnAlertas;
    private javax.swing.JButton btnCaracteristicas;
    private javax.swing.JButton btnCategorias;
    private javax.swing.JButton btnCrearproducto;
    private javax.swing.JButton btnEspecificacion;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnInformes;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVenta;
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables

 
}
