import java.sql.*;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class stock extends javax.swing.JPanel {

    Conexion conn;
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int id;
    
    private String nombreUsuario;
    
    public stock(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;  // Guardas el nombre de usuario
        initComponents();
        conn = new Conexion();  // Instanciar la conexión
        conn.conectar();
        txtproducto.setEditable(false);
        txtstock.setEnabled(false);
        btnAgregar.setEnabled(false);
        cn = conn.getConnection();
        
        lblUser.setText("Usuario: " + nombreUsuario);
    }
    
    
    void buscarProducto() {
    String idProducto = txtid.getText();

    if (idProducto.equals("")) {
        JOptionPane.showMessageDialog(null, "Debe ingresar el ID del producto");
    } else {
        try {
            // Consulta para verificar si el producto existe y obtener el nombre y stock
            String sql = "SELECT nombreProducto, stock FROM productos WHERE id = ?";
            PreparedStatement pstBuscar = cn.prepareStatement(sql);
            pstBuscar.setString(1, idProducto);
            ResultSet rs = pstBuscar.executeQuery();

            if (rs.next()) {
                // Producto encontrado, habilitar el campo para ingresar el stock adicional
                String nombreProducto = rs.getString("nombreProducto");
                int stockActual = rs.getInt("stock");

                // Mostrar el nombre del producto y stock actual
                txtproducto.setText(nombreProducto);  // Mostrar nombre del producto en el textbox
                JOptionPane.showMessageDialog(null, "Producto encontrado. Stock actual: " + stockActual);

                // Habilitar el campo para ingresar la cantidad de stock y el botón de actualización
                txtstock.setEnabled(true);
                btnAgregar.setEnabled(true);

                // Deshabilitar el campo de ID y el botón de búsqueda
                txtid.setEnabled(false);
                btnBuscar.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "El producto no existe");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al buscar el producto: " + e.getMessage());
        }
    }
 
}
    
    
    void actualizarStock() {
        String idProducto = txtid.getText();
        String cantidadStock = txtstock.getText();

        if (cantidadStock.equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar una cantidad de stock");
        } else {
            try {
                // Convertir la cantidad ingresada a número
                int cantidadNueva = Integer.parseInt(cantidadStock);

                // Consulta para actualizar el stock del producto
                String sqlActualizar = "UPDATE productos SET stock = stock + ? WHERE id = ?";
                PreparedStatement pstActualizar = cn.prepareStatement(sqlActualizar);
                pstActualizar.setInt(1, cantidadNueva);
                pstActualizar.setString(2, idProducto);
                pstActualizar.executeUpdate();

                JOptionPane.showMessageDialog(null, "Stock actualizado correctamente");
                
                
                String sqlInsertarMovimiento = "INSERT INTO historial_stock (id_producto, operacion, cantidad, usuario) VALUES (?, ?, ?, ?)";
                PreparedStatement pstMovimiento = cn.prepareStatement(sqlInsertarMovimiento);
                pstMovimiento.setString(1, idProducto); // ID del producto seleccionado
                pstMovimiento.setString(2, "entrada"); // 'entrada' o 'salida'
                pstMovimiento.setString(3, cantidadStock); // Cantidad agregada o retirada
                pstMovimiento.setString(4, nombreUsuario); // Usuario que realiza la operación
                pstMovimiento.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Se agrego el movimiento al historial");

                // Limpiar y resetear los campos
                txtid.setText("");
                txtstock.setText("");
                txtstock.setEnabled(false);
                btnAgregar.setEnabled(false);
                txtid.setEnabled(true);
                btnBuscar.setEnabled(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al actualizar el stock: " + e.getMessage());
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtproducto = new javax.swing.JTextField();
        txtstock = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("INGRESO DE STOCK PRODUCTOS");

        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidKeyTyped(evt);
            }
        });

        txtstock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtstockKeyTyped(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(13, 110, 253));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(13, 110, 253));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel3.setText("NOMBRE");

        jLabel4.setText("STOCK");

        lblUser.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addComponent(lblUser)
                .addGap(93, 93, 93))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(50, 50, 50)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser)
                    .addComponent(jLabel1))
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(314, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarProducto();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        actualizarStock();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyTyped
        char c = evt.getKeyChar();
        // Si no es un número (dígito) o la tecla de retroceso (para borrar), lo ignoramos
        if (!Character.isDigit(c)) {
            evt.consume(); // Evitar que el carácter se ingrese
        }
    }//GEN-LAST:event_txtidKeyTyped

    private void txtstockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstockKeyTyped
        char c = evt.getKeyChar();
        // Si no es un número (dígito) o la tecla de retroceso (para borrar), lo ignoramos
        if (!Character.isDigit(c)) {
            evt.consume(); // Evitar que el carácter se ingrese
        }
    }//GEN-LAST:event_txtstockKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtproducto;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables
}
